# Generated by Django 4.0.2 on 2022-04-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, default='-', max_length=300, null=True),
        ),
    ]
