# Generated by Django 4.0.2 on 2022-04-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='info',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='github',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='youtube',
        ),
    ]
