# Generated by Django 4.0.2 on 2022-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
