# Generated by Django 4.0.2 on 2022-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_like_count_account_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='github',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='youtube',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
