# Generated by Django 4.0.2 on 2022-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_like_count_account_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bio',
            new_name='info',
        ),
        migrations.AddField(
            model_name='account',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='youtube',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
