# Generated by Django 4.0.2 on 2022-04-14 07:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(upload_to=base.models.pdf_path),
        ),
    ]
