# Generated by Django 4.0.2 on 2022-02-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
