# Generated by Django 4.0.2 on 2022-04-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_note_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
