# Generated by Django 4.0.2 on 2022-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_note_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='views',
            new_name='view_count',
        ),
    ]
