# Generated by Django 4.0.2 on 2022-04-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_views_note_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
