# Generated by Django 4.0.2 on 2022-04-23 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_shelf_shelfitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelf', to=settings.AUTH_USER_MODEL),
        ),
    ]
