# Generated by Django 4.0.2 on 2022-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
