# Generated by Django 4.0.2 on 2022-04-27 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_note_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
